import { colors, fontFamily } from "@/src/constants";
import { statusBarHeight } from "@/src/hooks/statusBarHeight";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingTop: statusBarHeight + 23,
    paddingHorizontal: 28,
    position: "absolute",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  welcome: {
    fontFamily: fontFamily.medium,
    fontSize: 18,
    color: colors.white,
  },
  name: {
    fontFamily: fontFamily.semiBold,
    fontSize: 22,
    color: colors.white,
    paddingTop: 12,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 50,
    backgroundColor: colors.white,
    display: "flex",
  },
  containerCard: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 28,
    marginVertical: 30,
  },
  cardMaintenance: {
    backgroundColor: "#5c44f1",
    borderRadius: 20,
    padding: 10,
    width: 150,
    height: 150,
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    overflow: "hidden",
  },
  cardVehicle: {
    backgroundColor: "#6bbdff",
    borderRadius: 20,
    padding: 10,
    width: 150,
    height: 150,
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    overflow: "hidden",
  },
  cardNumber: {
    fontFamily: fontFamily.semiBold,
    fontSize: 40,
    color: colors.white,
  },
  cardText: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.white,
  },
  containerMaintenancesExpires: {
    paddingHorizontal: 28,
    paddingBottom: 28,
    gap: 20,
  },
  containerMaintenancesExpiresTitle: {
    color: "#3D3D3D",
    fontFamily: fontFamily.medium,
    fontSize: 22,
  },
  containerMaintenance: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    width: 283,
    height: 120,
    backgroundColor: colors.white,
    borderRadius: 20,
  },
  containerMaintenanceImage: {
    width: 80,
    height: 80,
    borderWidth: 1,
    borderColor: "#D3D3D3",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  containerMaintenanceContent: {
    gap: 2,
  },
  maintenanceTitle: {
    color: "#212121",
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
  },
  maintenanceSubTitle: {
    color: "#212121",
    fontFamily: fontFamily.regular,
    fontSize: 14,
  },
  maintenanceCar: {
    color: "#ABAFB1",
    fontFamily: fontFamily.regular,
    fontSize: 12,
  },
  containerMaintenancePrice: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  maintenancePrice: {
    color: "#40189D",
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  //
  containerVehicles: {
    paddingBottom: 28,
    gap: 20,
  },
  containerVehiclesTitle: {
    paddingLeft: 28,
    color: "#3D3D3D",
    fontFamily: fontFamily.medium,
    fontSize: 22,
  },
  containerVehicle: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    paddingLeft: 28,
    paddingTop: 20,
    width: "100%",
    height: 154,
    backgroundColor: colors.white,
  },
  containerVehicleImage: {
    width: 55,
    height: 55,
    borderWidth: 1,
    borderColor: "#D3D3D3",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  containerVehicleHeader: {
    gap: 7,
    paddingBottom: 10,
  },
  vehicleTitle: {
    color: "#212121",
    fontFamily: fontFamily.regular,
    fontSize: 14,
  },
  vehicleSubTitle: {
    color: "#212121",
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
  },
  containerVehiclePlaca: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  vehicleCar: {
    color: "#121212",
    fontFamily: fontFamily.medium,
    fontSize: 16,
  },
  containerVehiclePrice: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  vehiclePrice: {
    color: "#40189D",
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
});
